= WiFiNINA Library for Cypress PSoc Creator =

**Porting this to a C library**

I am in the middle of designing a system that historically I would likely have
used Arduino for, but I'm feeling adventurous, and want to use a Cypress PSoC
chipset instead (actually two of them, one ARM Cortex-M3, and one Cortex-M0).
Unfortunately, I can see no easy way to extend the IDE to use C++, so I'm
porting this library to C so I can use it, and have an Adafruit Airlift board
attached using SPI.

I have not yet decided if I intend to port future changes or not.  I have
removed the examples and the Arduino-specific packaging files.

**Modified to allow any pins to be used for Adafruit Airlift Boards**

Enables network connection (local and Internet) with the Arduino MKR WiFi 1010, Arduino MKR VIDOR 4000 and Arduino UNO WiFi Rev.2.

With this library you can instantiate Servers, Clients and send/receive UDP packets through WiFi. The board can connect either to open or encrypted networks (WEP, WPA). The IP address can be assigned statically or through a DHCP. The library can also manage DNS.

For more information about this library please visit us at
http://www.arduino.cc/en/Reference/WiFiNINA

== License ==

....
Copyright (c) 2019 Gavin Hurlbut.  All rights reserved.
Copyright (c) 2018 Arduino SA. All rights reserved.
Copyright (c) 2011-2014 Arduino LLC. All right reserved.
....

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
